
services:
  nestjs:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:  
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - mysql
    networks:
      - app-network

  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: test
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    networks:
      - app-network

  mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: adminpassword
      MONGO_INITDB_DATABASE: wallet
    ports:
      - "27018:27017"
    volumes:
      - mongodb_data:/data/db  # Referring to the volume
    command: ["mongod", "--bind_ip", "0.0.0.0"]  # 외부 연결 허용
    networks:
      - app-network

volumes:
  mongodb_data: {}  # Defining the volume


networks:
  app-network: